apiVersion: apps/v1
kind: Deployment
metadata:
  name: xml-deployment
  labels:
    app: xml-deployment
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmaps/xml-configmap.yaml") . | sha256sum }}

spec:
  replicas: {{ required "xmlDeployment.replicas was not specified" .Values.xmlDeployment.replicas }}
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      name: xml-deployment

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      name: xml-deployment
      labels:
        name: xml-deployment

    spec:
      volumes:
        - name: xml-configmap-volume
          configMap:
            name: xml-config

      containers:
      - name: xml-deployment
        image: {{ required "xmlDeployment.image.name was not specified" .Values.xmlDeployment.image.name }}:{{ required "xmlDeployment.image.tag was not specified" .Values.xmlDeployment.image.tag }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi
        ports:
          - name: nginx-port
            containerPort: 80

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20

        volumeMounts:
        - name: xml-configmap-volume
          mountPath: /tmp/config.xml
          subPath: config.xml

        env:
          - name: LOG_LEVEL
            value: {{ required "xmlDeployment.logLevel was not specified" .Values.xmlDeployment.logLevel }}

     