apiVersion: v1
kind: ConfigMap
metadata:
  name: xml-config
  labels:
    app: xml-deployment
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
data:
{{ (.Files.Glob "files/xml/config.xml").AsConfig | indent 2 }}

