---
# added to simplify reproduction of the issue
apiVersion: v1
kind: Namespace
metadata:
  name: web

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
  namespace: web
spec:
  ports:
  - port: 80
  selector:
    app: guestbook # fixed, was guestbook-web, needs to match pod labels
    tier: frontend
    
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: web  # fixed, was backend not matching the service namespace
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80  # fixed, was 80 not matching the service port and was the port in use inside of the container